### ISSUE TITLE
FS20_HudBar-V0.23Build17 not showing

### ISSUE THREAD

**Issue by sonicviz** [bm98/FS20_HudBar#1]
Nice idea, just testing it out. 

FS20_HudBar-V0.23Build17 seems to run ok, but it's not showing when started, so cannot even click on it to configure it.
No error message when starting by console, and it's showing as running in task manager, and has a transparent window up. 
Possibly because the configurations are not set, but you need to see it in order to be able to right click/configure?
 
FS20_HudBar-V0.22Build16, by comparison, shows up and works aok (manually configured previously).

Also suggest the configuration comes pre-configured as in the documentation as setting it up was a little unintuitive the first time.

**Comment by bm98** [comment]
Thanks for looking into it - I've changed the default Checked to OFF - but now if you start from scratch possibly have not one checked - my bad. 
Will be resolved today before sending it to the Flight Sim Shop...

**Comment by bm98** [comment]
Should be fixed in Build 0.24 B18

**Comment by sonicviz** [comment]
Thanks.
