### ISSUE TITLE
dataloader not detecting instalation/not creating db

### ISSUE THREAD

**Issue by fernyjbh** [bm98/FS20_HudBar#12]
I tried to use the dataloader, even the latest beta, but when I put my custom instalation folder (steam version) it throws this error:

ERR: MSFS Filestorage not found - pls. try to find the folder manually

But can't even use the littenavmap function, the program itself throws another an unhandled exception when clicking "start":

> See the end of this message for details on invoking 
> 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.IO.FileNotFoundException: Could not find file 'C:\Users\ferny\Documents\MSFS_HudBarSave\db\fs2020genApt.dblite'.
> File name: 'C:\Users\ferny\Documents\MSFS_HudBarSave\db\fs2020genApt.dblite'
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileInfo.get_Length()
>    at FacilityDataLoader.frmLoader.btStart_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> FacilityDataLoader
>     Assembly Version: 1.1.0.7
>     Win32 Version: 1.1.0.7
>     CodeBase: file:///D:/Games/MSFS%20STUFF/FS20_HudBar/dataLoader/FacilityDataLoader.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> DbgLib
>     Assembly Version: 1.0.0.5
>     Win32 Version: 1.0.0.5
>     CodeBase: file:///D:/Games/MSFS%20STUFF/FS20_HudBar/dataLoader/DbgLib.DLL
> ----------------------------------------
> BGLlib
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/Games/MSFS%20STUFF/FS20_HudBar/dataLoader/BGLlib.DLL
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4579.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> CoordLib
>     Assembly Version: 1.3.0.16
>     Win32 Version: 1.3.0.16
>     CodeBase: file:///D:/Games/MSFS%20STUFF/FS20_HudBar/dataLoader/CoordLib.DLL
> ----------------------------------------
> netstandard
>     Assembly Version: 2.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Checked permissions for mydocs/MSFS_HudBarSave, I have full permissions

Here is the debug log:**

> 2022-12-01T13:49:15.4287773-03:00¦DGBLog - Init
> Debug:       FacilityDataLoader, Version=1.1.0.7, Culture=neutral, PublicKeyToken=null
> Application: FacilityDataLoader, Version=1.1.0.7, Culture=neutral, PublicKeyToken=null
> OS Information:
>     Windows 10 Enterprise LTSC 2021  (2009) 6.2.9200.0 64-bits
>     Runtime: 4.0.30319.42000
>     .Net: .NET Framework 4.7.2
> Locale:
>     en-US    English (United States)
> Current Directory:
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader
> Files:
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\BGLlib.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\CoordLib.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\DbgLib.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\DEBUG_log.txt
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\FacilityDataLoader.exe
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\FSimFacilityDataLib.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\FSimFacilityIF.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\LiteDB.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\README.txt
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\System.Data.SQLite.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\x64\SQLite.Interop.dll
>     D:\Games\MSFS STUFF\FS20_HudBar\dataLoader\x86\SQLite.Interop.dll
> 2022-12-01T13:49:15.4327699-03:00¦AppVersion: FacilityDataLoader - 1.1.0.7
> 2022-12-01T13:49:15.4571431-03:00¦MsFolders.GetPackagePath_Int-Package Path STEAM is: (C:\Users\ferny\AppData\Roaming\Microsoft Flight Simulator)
> 2022-12-01T13:49:15.4571431-03:00¦ERROR: MsFolders.GetStoreInstalledPackagesPath_Int-Cannot find (C:\Users\ferny\AppData\Roaming\Microsoft Flight Simulator\LocalCache\UserCfg.opt)
> 2022-12-01T13:49:15.4581407-03:00¦MsFolders.GetInstalledPackagesPath_Int-Not found for STORE -- try STEAM
> 2022-12-01T13:49:15.4581407-03:00¦MsFolders.GetPackagePath_Int-Package Path STEAM is: (C:\Users\ferny\AppData\Roaming\Microsoft Flight Simulator)
> 2022-12-01T13:49:15.4591380-03:00¦MsFolders.GetInstalledPackagesPath_Int-PackagesPath is: (G:\MSFS2020)
> 2022-12-01T13:49:15.4591380-03:00¦ERROR: MsFolders.GetMSStorePath-Cannot find any Official\OneStore Path
> 2022-12-01T13:49:15.4601354-03:00¦MsFolders.GetNavBasePathNaviGraph-navigraph-navdata-base\scenery Path does not exist
> 2022-12-01T13:49:15.4601354-03:00¦Form1.frmLoader_Load-GenAptDBPath True: (C:\Users\ferny\Documents\MSFS_HudBarSave\db)
> 2022-12-01T13:49:15.4601354-03:00¦Form1.frmLoader_Load-LNM True: (C:\Users\ferny\AppData\Roaming\ABarthel\little_navmap_db\little_navmap_msfs.sqlite)
> 2022-12-01T13:49:15.4601354-03:00¦ERROR: MsFolders.GetMSStorePath-Cannot find any Official\OneStore Path
> 2022-12-01T13:49:15.4601354-03:00¦Form1.frmLoader_Load-OneStore False: ()
> 2022-12-01T13:49:15.4611326-03:00¦Form1.frmLoader_Load-Community True: (G:\MSFS2020\Community)
> 2022-12-01T13:49:15.4611326-03:00¦MsFolders.GetNavBasePathNaviGraph-navigraph-navdata-base\scenery Path does not exist
> 2022-12-01T13:49:15.4611326-03:00¦Form1.frmLoader_Load-Navigraph False: ()
> 2022-12-01T13:49:16.9656641-03:00¦Form1.btStart_Click-Called
> 2022-12-01T13:50:21.5008163-03:00¦Form1.btStart_Click-Called
> 2022-12-01T13:50:36.7378529-03:00¦Form1.frmLoader_FormClosing-About to Close
> 2022-12-01T13:50:36.7468561-03:00¦Form1.frmLoader_FormClosing-Finished

[main window error](https://i.imgur.com/wmp7BoL.png)

[exception](https://i.imgur.com/tKE679L.png)

**Comment by bm98** [comment]
Thank you for your report - I learned that the Steam version has it's files not in the place I assumed (I have only access to the MS Store version)
There is little doc about it...
But I think I can prepare a 'better' data loader over the weekend and would appreciate if you could help to make it work.
I will post that update here in GitHub later.

**Comment by bm98** [comment]
[dataLoader-V1.1.0.9.zip](https://github.com/bm98/FS20_HudBar/files/10146481/dataLoader-V1.1.0.9.zip)

OK - more than one issue to be resolved..
There is a data loader included V 1.1.0.9
Should no longer bail out when no database file is found (my bad..)
Should find the Steam content under  ..\Official\Steam  (tried OneStore before which is the MS path)

Could you find out if this version would work ??
Thank you :-)

**Comment by fernyjbh** [comment]
Thanks! I tried it, the db error seems to be resolved, I was able to generate the db via littlenavmap data, but if I try to do it via MSFS file storage I get a "sequence contains no elements" error. = https://pastebin.com/4sQ2QTvJ

[DEBUG_log.txt](https://github.com/bm98/FS20_HudBar/files/10146861/DEBUG_log.txt)

**Comment by bm98** [comment]
[dataLoader-V1.1.0.10.zip](https://github.com/bm98/FS20_HudBar/files/10147363/dataLoader-V1.1.0.10.zip)

Live is hard... had a hardcoded OneStore reference in an area untouched since the very beginning...
Anyway there is this new build which may now finally work with the MS files
Thanks for testing!

**Comment by fernyjbh** [comment]
Confirmed working everything now (in my system at least lol), via file storage and littlenavmap, and with and without a previous database file. Thanks for your time dedicated to this app!

**Comment by bm98** [comment]
Great... I will prepare the update then for tomorrow
Let's hope the Steam installation cannot vary that much.
Also thank you for helping out to resolve this issue.

**Comment by bm98** [comment]
Should be fixed in the latest release now
Closing this issue
