### ISSUE TITLE
Request: 3 additional RADNAV-Variables

### ISSUE THREAD

**Issue by dgausdiw** [bm98/FS20_HudBar#17]
Hey, thanks a lot for your work on the HudBar! Extremely useful tool.

I'd like to request three additional variables to be presentable in the HudBar:
- ADF2 Active / Standby
- Course of NAV1 (Course 1) - should be SIMCONNECT-Variable NAV OBS:1
- Course of NAV2 (Course 2) - should be SIMCONNECT-Variable NAV OBS:2

It would be awesome if you could include these variables in one of the upcoming versions of the HudBar.
Thank you!

**Comment by bm98** [comment]
Should be possible... :)

**Comment by dgausdiw** [comment]
Awesome, thanks! Looking forward to it :)

**Comment by bm98** [comment]
Could you double check if it is as intended?? BTW which aircraft features 2 ADFs apart from the A320/Boeing where one should not change the frequency from the HudBar (at least the A32NX complains...). I could not find one to test with...

![CrsFeature](https://github.com/bm98/FS20_HudBar/assets/7956007/50989d0f-811e-42ac-a23d-8f3f0d30006d)

**Comment by dgausdiw** [comment]
Looks good to me! Concerning your question: You're right, that's an Airliner thing. I use the HudBar only as a display though without changing any values (I use an X Touch Mini for that), so no changing functionality is fine for me. And as you said, the FBW doesn't accept changes, while the Fenix does.

**Comment by dgausdiw** [comment]
Thanks a lot for the fast consideration of my request! I saw and downloaded the update, but I'm currently not at home. I'll try the new version next week and will let you know :)

**Comment by dgausdiw** [comment]
Thanks a lot once again! I did some testing today; your additions work exactly like I wanted. Very happy about it :)
