### ISSUE TITLE
No values displayed - SimConnect Clash?

### ISSUE THREAD

**Issue by regturley** [bm98/FS20_HudBar#4]
I have installed the MSFS2020 HUD Bar, but no values are displayed. I use a navigation program - Plan-G - which uses SimConnect, and I wondered if there might be a clash between the two?

**Comment by bm98** [comment]
Default is all off but MSFS - so you have to right click and go to Configuration.
May be reading the Guide (PDF file) ;-)
Else let me know

**Comment by regturley** [comment]
Yes I did read the guide and I did configure the settings. I have now got the HUDBar connected and working, but I had to disable my SimConnect.xml file to do it. This file connects FS2020 to my navigation program on a second machine, where I display a moving map. I now have the following questions -
(1) Is it possible to edit my SimConnect.xml file such that I can have both HUDBar and my navigation program working?
(2) The HUDBar displayed the GS in purple and stayed at zero, does this variable not show?
(3) When flying the helicopter it is useful to have a radio-altimeter display, showing the height above ground level. Could this be added?
Thanks for your help, and for a very useful utility.

**Comment by regturley** [comment]
Since my last comment I discovered that HUDBar creates its own SimConnect.xml file in the ...LocalCache folder. I have found that by inserting the relevant chunks from my navigation program's SC.xml file I can have both working. Hooray! That answers my question 1. I have found the radio altimeter variable in the list, so that answers question 3. So I still have the question outstanding re the GS apparently not working.
I have noticed that the VSI does not show a leading zero when descending, could this be added?
Thanks again

**Comment by regturley** [comment]
Just spotted the up/down arrow on the VSI, its not easy to see, a minus sign or change to red would be easier to spot.

**Comment by bm98** [comment]
The SimConnect.xml is probably created by the MS DLL but not by HudBar, I have one there as well but the date is the same as other MS files - so I assume it is created on install?? Anyway the SimConnect.cfg in the HudBar folder must follow the SimConnect.xml and for other than standard you may have to tweak possibly the Config File in the HudBar install folder. (At least that is what I read). And then multiple instances of any SimConnect program should work in parallel.

In general the SimConnect capture is a bit shaky and depends on the planes use of stock or modified instrumentation.
GS (GroundSpeed) works here while using G1000 also with WT and 750 Mod but I found that some planes with their own GPS do not update the Sim properly (e.g. the new Garmin Nxi did in its 1st release not update towards the Sim and then values are not captured by any SimConnect app - may be it works now - did not checked it. Sometimes it is even between releases that things that worked do not longer or get back)
For the VSI - well I would not use red .. it is a bit scary and not used in any instrumentation for legit values.
In general I would add a second readout with +- signs so the user can chose from the two options. I cannot remove the arrow one else another user will call it missing...
I will collect some of the improvement suggestions for another release anyway.

**Comment by regturley** [comment]
OK Thanks, I'll await the new version with interest.
