### ISSUE TITLE
Feature Request: Keyboard Shortcut to hide and show

### ISSUE THREAD

**Issue by Strat919** [bm98/FS20_HudBar#7]
Please add a user configurable Keyboard shortcut to show and hide this addon. I use a program called Taskbar Hide 3.1.1 to accomplish this but it is something that has to be set up every time the Hudbar is used..... which is all the time:) Don't know how hard it would be, or even possible, but if the Hudbar became hidden when MSFS2020 is not the active window. 
Also it would be great if there were keyboard shortcuts to change profiles but can be easily done by right clicking on Hudbar. 

It will be a sad day if I were to update MSFS2020 and this didn't work:)

Keep up the fantastic work and I really do appreciate this mod!

**Comment by bm98** [comment]
Hi - great to hear..
Next Rel will have the possibilty to Hide/Show with fixed shortcut RCtrl+NumPad0 
Also switching profiles with RCtrl+NumPad1..5   (those shortcuts currently not default used in MSFS)
User configurable shortcuts is may be available in a later stage, making such a config GUI is a bit complicated..
I cannot see if MSFS is active or not - so automatically hiding is not possible/ and may be not wanted by all.
I will do some more testing and then upload a release here in a day or two.

**Comment by Strat919** [comment]
Hey..... I sure do appreciate that:) I'm trying to let everyone know how 
useful this mod is. I'm using it in a top bound tile config and it is 
difficult to use a browser at full screen without hiding it.
I think a lot of people will find the shortcuts very useful.... I know I will.

I'm also wondering... You already have the ability to engage autopilot 
functions like nav, hdg, vs mode etc. It would be so cool if you could for 
instance... place your cursor
over a field and change the value with the mouse wheel. Could something 
like that be done with simconnect? Just a thought.

Thanks again

David


At 08:10 PM 12/8/2021, you wrote:

**Comment by Strat919** [comment]
Awesome...... I saw on github the mouse wheel functions. A lot of people 
will like that:) Since you have the skills to pull all that off, another 
great addition might be.....
Adding a button to toggle auto throttle along with a mouse wheel field for 
increase decrease reference Air Speed. With some aircraft, it's hard to get 
to while trying to land when
everything is happening fast. Also, some aircraft have an auto throttle, 
just not inside the plane and not really meant to be used..... but hey it's 
all about fun:)

I'm not quite understanding the files on github. Are they what you are 
coding and not meant for use? There is no .exe file in all the files.

Thanks again



Hey..... I sure do appreciate that:) I'm trying to let everyone know how 
useful this mod is. I'm using it in a top bound tile config and it is 
difficult to use a browser at full screen without hiding it.
I think a lot of people will find the shortcuts very useful.... I know I will.

I'm also wondering... You already have the ability to engage autopilot 
functions like nav, hdg, vs mode etc. It would be so cool if you could for 
instance... place your cursor
over a field and change the value with the mouse wheel. Could something 
like that be done with simconnect? Just a thought.

Thanks again

David


At 08:10 PM 12/8/2021, you wrote:

**Comment by bm98** [comment]
Will look into the topic..

And on this site the package can be found under Releases. It is the main hub for me..
https://github.com/bm98/FS20_HudBar/releases
Open Assest and get the Zip File - it is the same as I will later upload to the FlightSim site.
Regs

**Comment by Strat919** [comment]
Hey..... are you familiar with a program called JoyToKey? I set all my 
joystick bindings with it instead of inside MSFS. For some reason it will 
not transmit the R CTRL 0, 1,2,3,4 to the Hudbar. I am a (near) expert in 
JoyToKey and have tested for about an hour now. I can set it in the sim 
with ADF2_100_DEC and it does work. R CTRL 0 DOES work with the keyboard, 
mouse button and other programs where I can transmit the R CTRL 0 
command.....just not JoyToKey. I have not seen JoyToKey to not work 
anywhere else whether in the sim or anywhere in windows.

Can you think of any reason why this doesn't work, or what could be 
different about the way your shortcuts work differently from standard 
windows? There is an option to set the CTRL key to direct input in JoyToKey 
but that doesn't work either.

Thanks




Awesome...... I saw on github the mouse wheel functions. A lot of people 
will like that:) Since you have the skills to pull all that off, another 
great addition might be.....
Adding a button to toggle auto throttle along with a mouse wheel field for 
increase decrease reference Air Speed. With some aircraft, it's hard to get 
to while trying to land when
everything is happening fast. Also, some aircraft have an auto throttle, 
just not inside the plane and not really meant to be used..... but hey it's 
all about fun:)

I'm not quite understanding the files on github. Are they what you are 
coding and not meant for use? There is no .exe file in all the files.

Thanks again



Hey..... I sure do appreciate that:) I'm trying to let everyone know how 
useful this mod is. I'm using it in a top bound tile config and it is 
difficult to use a browser at full screen without hiding it.
I think a lot of people will find the shortcuts very useful.... I know I will.

I'm also wondering... You already have the ability to engage autopilot 
functions like nav, hdg, vs mode etc. It would be so cool if you could for 
instance... place your cursor
over a field and change the value with the mouse wheel. Could something 
like that be done with simconnect? Just a thought.

Thanks again

David


At 08:10 PM 12/8/2021, you wrote:

**Comment by bm98** [comment]
I assume it is because I need to capture the Keyboard at lowest level to have it also when the App does not have the focus.
But JoyToKey may inject the keystrokes above and therefore the App does not see them.
There are other ways to capture the Windows Key inputs - only they are not so recommended (as I read)
The question is really where JoyToKey inserts the keys... 
I will have a look if I can find out.

**Comment by Strat919** [comment]
Thanks for looking into it:) I'm at the moment trying to find an emulator 
that will work as an in between that will pass the keyboard strokes from 
JoyToKey to the emulator to your app.

I'm hoping you can figure out the answer and won't have to do this:)

Thanks again



At 12:02 PM 12/10/2021, you wrote:

**Comment by Strat919** [comment]
Just thought I'd let you know I tried 4 or 5 joystick to keyboard emulators 
and none of them would send the commands to Hudbar......


Thanks for looking into it:) I'm at the moment trying to find an emulator 
that will work as an in between that will pass the keyboard strokes from 
JoyToKey to the emulator to your app.

I'm hoping you can figure out the answer and won't have to do this:)

Thanks again



At 12:02 PM 12/10/2021, you wrote:

**Comment by bm98** [comment]
I will exchange the Keyboard capture - the RawInput used will only capture from real attached keyboards or emulations that are connected as HID devices and not from Sent Keystrokes  - which is what most such Tools will do (did it myself..)
Just wait a moment..

**Comment by Strat919** [comment]
Thanks:)

At 04:23 PM 12/10/2021, you wrote:

**Comment by bm98** [comment]
You may give it a try - it is V0.38 **B34**
Just go to Assets and get the Zip again.
Regs

**Comment by Strat919** [comment]
Just wanted you to be aware that the right CTRL 0 shortcut is also the 
default shortcut to reset zoom in browsers. A great feature of the hide 
show shortcut is so you can have the hudbar in top position and  the 
ability to hide when you have a browser up. I assume, like myself, everyone 
has a different zoom level set for different web pages. Just thought I'd 
bring it up:)

Thanks


At 04:23 PM 12/10/2021, you wrote:

**Comment by Strat919** [comment]
Works Perfectly! Thanks very much:)


At 06:27 PM 12/10/2021, you wrote:

**Comment by Strat919** [comment]
I see you are on the move again:) Thanks for adding a custom config for 
shortcuts..... sweet!

Another idea if it were not too difficult. It would be cool, and very 
helpful if there was an auto hide feature similar to auto hide in the 
windows taskbar. You just move your mouse cursor to the side of the screen 
where the hudbar is, and it pops out. It stays out until focus is taken 
away. Also a spot on the hudbar where you click and it remains out until 
you hit that spot again. I've used a few apps over the years that have this 
feature. I'm hesitant to use the side bars because of the width taken up. 
Not by any means necessary, just thought I'd throw it out there:)

Thanks!



At 06:27 PM 12/10/2021, you wrote:

**Comment by bm98** [comment]
Implemented and closed
