### ISSUE TITLE
Audio Init fails sometimes

### ISSUE THREAD

**Issue by bm98** [bm98/FS20_HudBar#9]
Audio Init fails for some reasons - Exception fall through and the program fails

**Comment by bm98** [comment]
Added some more checks to Audio Init
Also corrected code for invalid handles
Test Versio
[HudBar-Test-V0.44B41.zip](https://github.com/bm98/FS20_HudBar/files/8104634/HudBar-Test-V0.44B41.zip)
n attached. (only some files to be replaced in V0.43)

**Comment by sonicviz** [comment]
Testing, thanks. 

Any way of transferring existing presets/configs to a new version?

**Comment by bm98** [comment]
About to release an update...
For the settings - if you put the files in the same folder it retains the updates, If the location changes it starts from scratch.
This is Win AppSettings behavior.
You could manually copy them I think:
The location is 
C:\Users\<User>\AppData\Local\FS20_HudBar\FS20_HudBar.exe_Url_<stuff>\<BuildVersion>\user.config
The <stuff> part changes for each location the program is run from - I would assume that if you copy the <Version> folder into the new one and then delete the latest version which has been created by the first run - the next run would use the previous version to update from.
A bit complicated but I used to do this for some regresstion testing from old to new versions.

RE Wind arrow - thought about that, it needs a new Item that is a Graphic which is Drawn - I have to see if the height is OK to make a recognizeable arrow .. and then some math to get it right (but I have this done already for another proj)

Thanks for helping :)

**Comment by sonicviz** [comment]
Awesome, thanks.

**Comment by bm98** [comment]
Seems to be fixed - closing this one
